train:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 30
        p: 0.1
      - _target_: src.transforms.spec_augs.TimeStretch
        fixed_rate: 1.2
